apiVersion: apps/v1
kind: Deployment 
metadata:
  name: laravel-products-api
  namespace: aplicacion 
  labels:
    app: laravel-products-api
spec:
  revisionHistoryLimit: 2 
  strategy:
    type: RollingUpdate 
  replicas: 3 
  selector:
    matchLabels:
      app: laravel-products-api
  template: 
    metadata:
      labels: 
        app: laravel-products-api
    spec:
      containers:
      - name: laravel-products-api
        image: mauixfull/laravel-inventario-api:v2 
        ports:
        - name: http
          containerPort: 8000
        env:
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: dbconfigmap
                key: DB_PORT
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DB_HOST
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DB_PASSWORD
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DB_DATABASE