apiVersion: v1
kind: Service 
metadata:
  name: inventario-api
  namespace: aplicacion 
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80 
    targetPort: http
  selector:
    app: inventario-api

