apiVersion: v1
kind: Service 
metadata:
  name: laravel-products-api 
  namespace: default 
spec:
  type: LoadBalancer 
  ports:
  - name: http
    port: 8000
    targetPort: http
  selector:
    app: laravel-products-api